services:
  - type: web
    name: kwikflip
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0
    envVars:
      - key: PYTHONUNBUFFERED
        value: true
      - key: PYTHONPATH
        value: .
      - key: STREAMLIT_SERVER_PORT
        value: ${PORT}
      - key: STREAMLIT_SERVER_ADDRESS
        value: 0.0.0.0
